name: netperf

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test-maas-connection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: executing remote ssh commands
        id: ssh1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm netperf.tcpstream.0910.sh
            wget https://github.com/usernet-infocom23/usernet-test/raw/main/netperf.tcpstream.0910.sh
            chmod +x netperf.tcpstream.0910.sh
            ./netperf.tcpstream.0910.sh
      - name: retry executing remote ssh commands
        id: ssh2
        if: ${{ failure() && steps.ssh1.outcome == 'failure' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          timeout: 5m
          script: |
            rm netperf.tcpstream.0910.sh
            wget https://github.com/usernet-infocom23/usernet-test/raw/main/netperf.tcpstream.0910.sh
            chmod +x netperf.tcpstream.0910.sh
            ./netperf.tcpstream.0910.sh
      - name: Download Result File
        if: ${{ always() && ((steps.ssh1.outcome.exit_code == 0) || (steps.ssh2.outcome.exit_code == 0)) }}
        run: |
          wget https://usernet-paper-project.s3.ap-northeast-2.amazonaws.com/result.zip
      - name: Upload
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.zip
